"""change_multiplier_to_float

Revision ID: 3a1e8abb1cda
Revises: 9d8b4c2a1f3e
Create Date: 2026-02-17 18:24:36.032008

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3a1e8abb1cda'
down_revision = '9d8b4c2a1f3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requires batch mode for column alterations
    with op.batch_alter_table('cfg_data_points', schema=None) as batch_op:
        batch_op.alter_column('multiplier',
                   existing_type=sa.INTEGER(),
                   type_=sa.Float(),
                   existing_nullable=False,
                   existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requires batch mode for column alterations
    with op.batch_alter_table('cfg_data_points', schema=None) as batch_op:
        batch_op.alter_column('multiplier',
                   existing_type=sa.Float(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   existing_server_default=sa.text('1'))
    # ### end Alembic commands ###
