"""initial schema

Revision ID: b1f131592650
Revises: 
Create Date: 2026-01-03 08:25:21.816735

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b1f131592650'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historian_hourly_rollups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plc_id', sa.String(length=200), nullable=False),
    sa.Column('datapoint_id', sa.String(length=200), nullable=False),
    sa.Column('avg_value', sa.Float(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_start', 'plc_id', 'datapoint_id', name='uq_rollup_bucket_plc_dp')
    )
    op.create_index(op.f('ix_historian_hourly_rollups_bucket_start'), 'historian_hourly_rollups', ['bucket_start'], unique=False)
    op.create_index(op.f('ix_historian_hourly_rollups_datapoint_id'), 'historian_hourly_rollups', ['datapoint_id'], unique=False)
    op.create_index(op.f('ix_historian_hourly_rollups_plc_id'), 'historian_hourly_rollups', ['plc_id'], unique=False)
    op.create_table('historian_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plc_id', sa.String(length=200), nullable=False),
    sa.Column('datapoint_id', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historian_samples_datapoint_id'), 'historian_samples', ['datapoint_id'], unique=False)
    op.create_index(op.f('ix_historian_samples_plc_id'), 'historian_samples', ['plc_id'], unique=False)
    op.create_index(op.f('ix_historian_samples_ts'), 'historian_samples', ['ts'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('task_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_templates_name'), 'task_templates', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=True)
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alarm_id', sa.String(length=80), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('acked', sa.Boolean(), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('acked_by_client_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['acked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarms_acked'), 'alarms', ['acked'], unique=False)
    op.create_index(op.f('ix_alarms_alarm_id'), 'alarms', ['alarm_id'], unique=True)
    op.create_index(op.f('ix_alarms_severity'), 'alarms', ['severity'], unique=False)
    op.create_index(op.f('ix_alarms_ts'), 'alarms', ['ts'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('command_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plc_name', sa.String(length=200), nullable=False),
    sa.Column('datapoint_id', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_command_id'), 'commands', ['command_id'], unique=True)
    op.create_index(op.f('ix_commands_created_at'), 'commands', ['created_at'], unique=False)
    op.create_index(op.f('ix_commands_datapoint_id'), 'commands', ['datapoint_id'], unique=False)
    op.create_index(op.f('ix_commands_plc_name'), 'commands', ['plc_name'], unique=False)
    op.create_index(op.f('ix_commands_status'), 'commands', ['status'], unique=False)
    op.create_index(op.f('ix_commands_user_id'), 'commands', ['user_id'], unique=False)
    op.create_table('config_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('yaml_path', sa.String(length=500), nullable=False),
    sa.Column('before_yaml', sa.Text(), nullable=False),
    sa.Column('after_yaml', sa.Text(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('backup_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts', 'yaml_path', 'id', name='uq_config_revisions_ts_path_id')
    )
    op.create_index(op.f('ix_config_revisions_action'), 'config_revisions', ['action'], unique=False)
    op.create_index(op.f('ix_config_revisions_ts'), 'config_revisions', ['ts'], unique=False)
    op.create_index(op.f('ix_config_revisions_yaml_path'), 'config_revisions', ['yaml_path'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_equipment_code'), 'equipment', ['equipment_code'], unique=True)
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_sha256', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_sha256'), 'refresh_tokens', ['token_sha256'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission')
    )
    op.create_table('server_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('logger', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_logs_level'), 'server_logs', ['level'], unique=False)
    op.create_index(op.f('ix_server_logs_source'), 'server_logs', ['source'], unique=False)
    op.create_index(op.f('ix_server_logs_ts'), 'server_logs', ['ts'], unique=False)
    op.create_index(op.f('ix_server_logs_user_id'), 'server_logs', ['user_id'], unique=False)
    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_name'), 'spare_parts', ['name'], unique=False)
    op.create_index(op.f('ix_spare_parts_part_code'), 'spare_parts', ['part_code'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('config_revision_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_revision_id'], ['config_revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_ts'), 'audit_logs', ['ts'], unique=False)
    op.create_table('breakdowns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakdowns_equipment_id'), 'breakdowns', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_breakdowns_resolved'), 'breakdowns', ['resolved'], unique=False)
    op.create_index(op.f('ix_breakdowns_ts'), 'breakdowns', ['ts'], unique=False)
    op.create_table('command_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('command_row_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['command_row_id'], ['commands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_events_command_row_id'), 'command_events', ['command_row_id'], unique=False)
    op.create_index(op.f('ix_command_events_status'), 'command_events', ['status'], unique=False)
    op.create_index(op.f('ix_command_events_ts'), 'command_events', ['ts'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cron', sa.String(length=200), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('task_template_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_template_id'], ['task_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_enabled'), 'schedules', ['enabled'], unique=False)
    op.create_index(op.f('ix_schedules_name'), 'schedules', ['name'], unique=False)
    op.create_index(op.f('ix_schedules_next_run_at'), 'schedules', ['next_run_at'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('task_template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_role_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_template_id'], ['task_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_created_at'), 'work_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_orders_equipment_id'), 'work_orders', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_work_order_code'), 'work_orders', ['work_order_code'], unique=True)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('qty_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['spare_parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_part_id'), 'inventory_transactions', ['part_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_ts'), 'inventory_transactions', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_transactions_ts'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_part_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_work_orders_work_order_code'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_equipment_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_created_at'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_schedules_next_run_at'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_name'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_enabled'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_command_events_ts'), table_name='command_events')
    op.drop_index(op.f('ix_command_events_status'), table_name='command_events')
    op.drop_index(op.f('ix_command_events_command_row_id'), table_name='command_events')
    op.drop_table('command_events')
    op.drop_index(op.f('ix_breakdowns_ts'), table_name='breakdowns')
    op.drop_index(op.f('ix_breakdowns_resolved'), table_name='breakdowns')
    op.drop_index(op.f('ix_breakdowns_equipment_id'), table_name='breakdowns')
    op.drop_table('breakdowns')
    op.drop_index(op.f('ix_audit_logs_ts'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_spare_parts_part_code'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_name'), table_name='spare_parts')
    op.drop_table('spare_parts')
    op.drop_index(op.f('ix_server_logs_user_id'), table_name='server_logs')
    op.drop_index(op.f('ix_server_logs_ts'), table_name='server_logs')
    op.drop_index(op.f('ix_server_logs_source'), table_name='server_logs')
    op.drop_index(op.f('ix_server_logs_level'), table_name='server_logs')
    op.drop_table('server_logs')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_sha256'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_code'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_config_revisions_yaml_path'), table_name='config_revisions')
    op.drop_index(op.f('ix_config_revisions_ts'), table_name='config_revisions')
    op.drop_index(op.f('ix_config_revisions_action'), table_name='config_revisions')
    op.drop_table('config_revisions')
    op.drop_index(op.f('ix_commands_user_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_status'), table_name='commands')
    op.drop_index(op.f('ix_commands_plc_name'), table_name='commands')
    op.drop_index(op.f('ix_commands_datapoint_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_created_at'), table_name='commands')
    op.drop_index(op.f('ix_commands_command_id'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_alarms_ts'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_severity'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_alarm_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_acked'), table_name='alarms')
    op.drop_table('alarms')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_task_templates_name'), table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_historian_samples_ts'), table_name='historian_samples')
    op.drop_index(op.f('ix_historian_samples_plc_id'), table_name='historian_samples')
    op.drop_index(op.f('ix_historian_samples_datapoint_id'), table_name='historian_samples')
    op.drop_table('historian_samples')
    op.drop_index(op.f('ix_historian_hourly_rollups_plc_id'), table_name='historian_hourly_rollups')
    op.drop_index(op.f('ix_historian_hourly_rollups_datapoint_id'), table_name='historian_hourly_rollups')
    op.drop_index(op.f('ix_historian_hourly_rollups_bucket_start'), table_name='historian_hourly_rollups')
    op.drop_table('historian_hourly_rollups')
    # ### end Alembic commands ###
