data_points:
  "LO-SUC PRES ALARM": 40072
  "LO-SUC PRES CUTOUT": 40073
  "HI-DISH PRES ALARM": 40074
  "HI-DISH PRES CUTOUT": 40075
  "HI-DISH TEMP ALARM": 40076
  "HI-DISH TEMP CUTOUT": 40077
  "HI-OIL TEMP ALARM": 40078
  "HI-OIL TEMP CUTOUT": 40079
  "SEPARATOR TEMP ALARM": 40080
  "SEPARATOR TEMP CUTOUT": 40081
  "FILTER PRES DIFF ALARM": 40082
  "FILTER PRES DIFF CUTOUT": 40083
  "OIL PRES DIFF ALARM": 40084
  "OIL PRES DIFF CUTOUT": 40085
  "AUX CONTROL-1 CUTOUT": 40086
  "AUX CONTROL-2 CUTOUT": 40087
  "LO-OIL LEVEL ALARM": 40088
  "COMPRESSOR FB FAIL": 40089
  "LUBE OIL PUMP FB FAIL": 40090
  "HI-MOTOR CURRENT ALARM": 40091
  "HI-MOTOR CURRENT CUTOUT": 40092
  "EMER PB PRESSED": 40093
  "OIL PUMP FEEDBACK": 40094
  "COMPRESSOR FEEDBACK": 40095
  "LO-OIL TEMP ALARM": 40096
  "LO-OIL TEMP CUTOUT": 40097
  "LIQ SLAGGING ALARM": 40098
  "LIQ SLAGGING CUTOUT": 40099
  "LO PHE CHILLER TEMP ALARM": 40100
  "LO PHE CHILLER TEMP CUTOUT": 40101
  "LO MOTOR CURRENT CUTOUT": 40102
  "SV POS HIGHER THAN 5%": 40103
