data_points:
  "EVAP_COND_1_CTRL_STS": 42022
  "EVAP_COND_1_CTRL_STS2": 42040
  "EVAP_COND_2_CTRL_STS": 42023
  "EVAP_COND_2_CTRL_STS2": 42041
  "EVAP_COND_3_CTRL_STS": 42037
  "EVAP_COND_3_CTRL_STS2": 42042
  "EVAP_COND_WT_PUMP1_CTRL_STS": 42026
  "EVAP_COND2_WT_PUMP1_CTRL_STS": 42028
  "EXTNGEVAP_COND_WT_PUMP_1_CTRL_STS": 42099
  "EVAP_COND_PRESSURE_OUT": 40424
  "EVAP_COND_SP_SLV1": 40444
  "EVAP_COND_DEDBND_SLV_1": 40448
  "EVAP_COND_SP_SLV2": 40450
  "EVAP_COND_DEDBND_SLV_2": 40454
  "EVAP_COND_STT_TIME_SLV1": 40456
  "EVAP_COND_STT_TIME_ACT_SLV1": 40458
  "EVAP_COND_STP_TIME_SLV1": 40460
  "EVAP_COND_STP_TIME_ACT_SLV1": 40462
  "EVAP_COND_STT_TIME_SLV2": 40464
  "EVAP_COND_STT_TIME_ACT_SLV2": 40466
  "EVAP_COND_STP_TIME_SLV2": 40468
  "EVAP_COND_STP_TIME_ACT_SLV2": 40470
  "EVAP_COND_WT_PMP_1RUN_HR": 40514
  "EVAP_COND_WT_PMP_2RUN_HR": 40516
  # "EXISTING_EVAP_COND_WT_PUMP_FB": 40004.4
  "EVAP_COND_22_CTRL_STS": 43000
  "EVAP_COND_22_CTRL_STS2": 43001
  "EVAP_COND_PRESSURE_MIN": 40428
  "EVAP_COND_PRESSURE_MAX": 40430
  # "EVAP_COND_1_WT_PMP_1_FB_FAIL": 1405.0
  # "EVAP_COND_2_WT_PMP_1_FB_FAIL": 1405.1
  # "EVAP_COND_3_WT_PMP_1_FB_FAIL": 1405.2
  # "EVAP_COND_1_FB_FAIL": 1405.3
  # "EVAP_COND_2_FAN_1_3_FB_FAIL": 1405.4
  # "EVAP_COND_3_FB_FAIL": 1405.5
  # "EVAP_COND_2_FAN_4_6_FB_FAIL": 1405.6
  #"EVAP_COND_WT_PMP_3RUN_HR": 518
  #"EVAP_COND_1WT_PMP_RUN_HR": 3198
  #"EVAP_COND_2WT_PMP_RUN_HR": 3200
  #"EVAP_COND_3WT_PMP_RUN_HR": 3202
  #"EVAP_COND_1_RUN_HR": 3048
  #"EVAP_COND_2_RUN_HR": 3050
  #"EVAP_COND_3_RUN_HR": 3052
  "COND1_MAINTENANCE_MODE": 40286
  "COND2_MASTER_FROM_SCADA": 40286
  "COND2_MAINTENANCE_MODE": 40286
  "COND3_MASTER_FROM_SCADA": 40286
  "COND3_MAINTENANCE_MODE": 40286
  "COND1_MASTER_FROM_SCADA": 40286
  "COND1_SLAVE_STATUS": 40288
  "COND1_MASTER": 40286
  "COND2_MASTER": 40286
  "COND3_MASTER": 40286
  "COND2_SLAVE_STATUS": 40290
  "COND3_SLAVE_STATUS": 40291