data_points:
  "HEADER_TEMP_LQD_AMONIA_PMP_5OUT": 40104
  "INLET_TEMP_FALING_FLM_CHILROUT": 40106
  "LIQD_TEMP_HEADER_EVAP_CONDOUT": 40092
  "HEADER_TEMP_LQD_AMONIA_PMP_40OUT": 40096
  "OUTLT_TEMP_FALING_FLM_CHILROUT": 40108
  "INLT_TMP_THO_SYPN_COLR_COMP1OT": 40110
  "OUTLT_TMP_THO_SYPN_COLR_COMP1OT": 40112
  "INLT_TMP_THRMO_SYPN_COLR_COMP2OT": 40114
  "OUTLT_TMP_THO_SYPN_COLR_COMP3OT": 40116
  "OUTLT_TMP_THO_SYPN_COLR_COMP4OT": 40118
  "FROZN_ROOM1_TEMP_OUT": 40120
  "FROZN_ROOM2_TEMP_OUT": 40122
  "FROZN_ROOM3_TEMP_OUT": 40124
  "FROZN_ROOM4_TEMP_OUT": 40126
  "FROZN_ROOM5_TEMP_OUT": 40128
  "FROZN_ROOM6_TEMP_OUT": 40130
  "PACK_HOUSE_TEMP_OUT": 40132
  "PACKING_AREA_TEMP_OUT": 40134
  "COLD_STORE1_TEMP_OUT": 40136
  "COLD_STORE2_TEMP_OUT": 40138
  "ANTE_ROOM_TEMP_OUT": 40140
  "IQF_TEMP_OUT": 40142
  "LIQD_TEMP_HDR_EVAP_COND_MIN": 40156
  "LIQD_TEMP_HDR_EVAP_COND_MAX": 40158
  "HDR_TEMP_LQD_AMONIA_PMP_40_MIN": 40166
  "HDR_TEMP_LQD_AMONIA_PMP_40_MAX": 40164
  "HDR_TEMP_LQD_AMONIA_PMP_30_MIN": 40172
  "HDR_TEMP_LQD_AMONIA_PMP_30_MAX": 40174
  "HDR_TEMP_LQD_AMONIA_PMP_5_MAX": 40182
  "INLET_TEMP_FALING_FLM_CHILR_MIN": 40184
  "INLET_TEMP_FALING_FLM_CHILR_MAX": 40186
  "OUTLT_TEMP_FALING_FLM_CHILR_MIN": 40188
  "OUTLT_TEMP_FALING_FLM_CHILR_MAX": 40190
  "FROZN_ROOM1_TEMP_MIN": 40212
  "FROZN_ROOM1_TEMP_MAX": 40214
  "FROZN_ROOM2_TEMP_MIN": 40216
  "FROZN_ROOM2_TEMP_MAX": 40218
  "FROZN_ROOM3_TEMP_MIN": 40220
  "FROZN_ROOM3_TEMP_MAX": 40222
  "FROZN_ROOM4_TEMP_MIN": 40224
  "FROZN_ROOM4_TEMP_MAX": 40226
  "FROZN_ROOM5_TEMP_MIN": 40228
  "FROZN_ROOM5_TEMP_MAX": 40230
  "FROZN_ROOM6_TEMP_MIN": 40232
  "FROZN_ROOM6_TEMP_MAX": 40236
  "PACK_HOUSE_TEMP_MIN": 40238
  "PACK_HOUSE_TEMP_MAX": 40240
  "PACKING_AREA_TEMP_MIN": 40242
  "PACKING_AREA_TEMP_MAX": 40244
  "COLD_STORE1_TEMP_MIN": 40246
  "COLD_STORE1_TEMP_MAX": 40248
  "COLD_STORE2_TEMP_MIN": 40250
  "COLD_STORE2_TEMP_MAX": 40252
  "ANTE_ROOM_TEMP_MIN": 40254
  "ANTE_ROOM_TEMP_MAX": 40256
  "IQF_TEMP_MIN": 40258
  "IQF_TEMP_MAX": 40260
  "FROZN_ROOM3_TEMP_HIGH_SP": 41638
  "FROZN_ROOM3_TEMP_LOW_SP": 41640
  "FROZN_ROOM4_TEMP_HIGH_SP": 41654
  "FROZN_ROOM4_TEMP_LOW_SP": 41656
  "FROZN_ROOM5_TEMP_HIGH_SP": 41668
  "FROZN_ROOM5_TEMP_LOW_SP": 41670
  "FROZN_ROOM6_TEMP_HIGH_SP": 41684
  "FROZN_ROOM2_TEMP_HIGH_SP": 41622
  "FROZN_ROOM2_TEMP_LOW_SP": 41624
  "FROZN_ROOM6_TEMP_LOW_SP": 41686
  "ANTE_ROOM_TEMP_MAX_SP_LLSV": 41538
  "ANTE_ROOM_TEMP_MIN_SP_LLSV": 41540
  "PACK_HOUSE_TEMP_MAX_SP_LLSV": 41328
  "PACK_HOUSE_TEMP_MIN_SP_LLSV": 41330
  "PACKING_AREA_TEMP_MIN_SP_LLSV": 41334
  "PACKING_AREA_TEMP_MAX_SP_LLSV": 41332
  "COMP_4_LO_OIL_TEMP_ALARM": 41351
  "COMP_4_LO_OIL_TEMP_CUTOUT": 41351
  "COMP_4_LO_PHE_CHILLER_TEMP_ALARM": 41351
  "COMP_4_LO_PHE_CHILER_TEMP_CTOUT": 41351
  #"IQF_TEMP_HIGH_SP": 1382
  #"IQF_TEMP_MIN_SP": 1384