data_points:
  "FRZN_ROOM1_DFRST_LLSV_CLS_TIME": 40542
  #"FRZN_ROOM1_DEFRST_STT_FROM_SCADA": 40546.0
  #"FRZN_ROOM1_DEFRST_STP_FROM_SCADA": 40546.1
  "FRZN_ROOM1_DFRT_FAN_UNT_OFF_TIM": 40544
  "FRN_RM1_DFRT_FAN_UNT_OFF_ACT_TIM": 40545
  "FRZN_ROOM1_HGSV_ON_TIME": 40550
  "FRZN_ROOM1_HGSV_ON_TIME_ACT_TIME": 40547
  "FRZN_ROOM1_DFRST_PUMP_ON_TIME": 40548
  "FRZN_ROM1_DFST_PUMP_ON_ACT_TIME": 40549
  "FRZN_ROM1_DFRST_LLSV_ON_TIME": 40551
  "FRZN_ROM1_DFRST_LLSV_ON_ACT_TIME": 40552
  #"FROZEN_ROOM_1UNIT1_SELECTED": 40600.0
  "FROZN_ROOM1_TEMP_LOW_SP": 40560
  "FROZN_ROOM1_TEMP_HIGH_SP": 40562
  "FZN_ROOM1_DFST_LLSV_CLS_ACT_TIM": 40543
  ##"FROZEN_ROOM_1UNIT2_SELECTED": 40600.4
  #"FROZEN_ROOM_2UNIT1_SELECTED": 40601.0
  #"FROZEN_ROOM_2UNIT2_SELECTED": 40601.1
  #"FROZEN_ROOM_3UNIT1_SELECTED": 40601.2
  #"FROZEN_ROOM_3UNIT2_SELECTED": 40601.3
  #"FROZEN_ROOM_4UNIT1_SELECTED": 40601.4
  #"FROZEN_ROOM_4UNIT2_SELECTED": 40601.5
  ##"FROZEN_ROOM_5UNIT1_SELECTED": 40601.6
  #"FROZEN_ROOM_5UNIT2_SELECTED": 40601.7
  #"FROZEN_ROOM_6UNIT1_SELECTED": 40601.8
  #"FROZEN_ROOM_6UNIT2_SELECTED": 40601.9
  "FRZN_ROOM2_DEFRST_STT_FROM_SCADA": 40602
  "FRZN_ROOM2_DEFRST_STP_FROM_SCADA": 40602
  "FRZN_ROOM2_DFRST_LLSV_CLS_TIME": 41612
  "FZN_ROOM2_DFST_LLSV_CLS_ACT_TIM": 41613
  "FRZN_ROOM2_DFRT_FAN_UNT_OFF_TIM": 41614
  "FRN_RM2_DFRT_FAN_UNT_OFF_ACT_TIM": 41615
  "FRZN_ROOM2_HGSV_ON_TIME": 41616
  "FRZN_ROOM2_HGSV_ON_TIME_ACT_TIME": 41617
  "FRZN_ROM2_DFST_PUMP_ON_ACT_TIME": 41619
  "FRZN_ROOM2_DFRST_PUMP_ON_TIME": 41618
  "FRZN_ROM2_DFRST_LLSV_ON_TIME": 41620
  "FRZN_ROM2_DFRST_LLSV_ON_ACT_TIME": 41621
  "FRZN_ROOM3_DEFRST_STT_FROM_SCADA": 40602
  "FRZN_ROOM3_DEFRST_STP_FROM_SCADA": 40602
  "FRZN_ROOM3_DFRST_LLSV_CLS_TIME": 41626
  "FZN_ROOM3_DFST_LLSV_CLS_ACT_TIM": 41627
  "FRZN_ROOM3_DFRT_FAN_UNT_OFF_TIM": 41628
  "FRN_RM3_DFRT_FAN_UNT_OFF_ACT_TIM": 41630
  "FRZN_ROOM3_DFRST_PUMP_ON_TIME": 41631
  "FRZN_ROM3_DFST_PUMP_ON_ACT_TIME": 41632
  "FRZN_ROOM3_HGSV_ON_TIME": 41633
  "FRZN_ROOM3_HGSV_ON_TIME_ACT_TIME": 41634
  "FRZN_ROM3_DFRST_LLSV_ON_TIME": 41635
  "FRZN_ROM3_DFRST_LLSV_ON_ACT_TIME": 41636
  
  "FRZN_ROOM4_DEFRST_STT_FROM_SCADA": 40602
  "FRZN_ROOM4_DEFROSTING_STT": 40602
  "FRZN_ROOM4_DEFRST_STP_FROM_SCADA": 40602
  "FRZN_ROOM4_DFRST_LLSV_CLS_TIME": 41642
  "FZN_ROOM4_DFST_LLSV_CLS_ACT_TIM": 41643
  "FRZN_ROOM4_DFRT_FAN_UNT_OFF_TIM": 41644
  "FRN_RM4_DFRT_FAN_UNT_OFF_ACT_TIM": 41645
  "FRZN_ROOM4_HGSV_ON_TIME": 41646
  "FRZN_ROOM4_HGSV_ON_TIME_ACT_TIME": 41647
  "FRZN_ROOM4_DFRST_PUMP_ON_TIME": 41648
  "FRZN_ROM4_DFST_PUMP_ON_ACT_TIME": 41649
  "FRZN_ROM4_DFRST_LLSV_ON_TIME": 41650
  "FRZN_ROM4_DFRST_LLSV_ON_ACT_TIME": 41651
  
  "FRZN_ROOM5_DEFRST_STT_FROM_SCADA": 40602
  "FRZN_ROOM5_DEFROSTING_STT": 40602
  "FRZN_ROOM5_DEFRST_STP_FROM_SCADA": 40602
  "FRZN_ROOM5_DFRST_LLSV_CLS_TIME": 41658
  "FZN_ROOM5_DFST_LLSV_CLS_ACT_TIM": 41659
  "FRZN_ROOM5_DFRT_FAN_UNT_OFF_TIM": 41660
  "FRN_RM5_DFRT_FAN_UNT_OFF_ACT_TIM": 41661
  "FRZN_ROOM5_HGSV_ON_TIME": 41662
  "FRZN_ROOM5_HGSV_ON_TIME_ACT_TIME": 41663
  "FRZN_ROOM5_DFRST_PUMP_ON_TIME": 41664
  "FRZN_ROM5_DFST_PUMP_ON_ACT_TIME": 41665
  "FRZN_ROM5_DFRST_LLSV_ON_TIME": 41666
  "FRZN_ROM5_DFRST_LLSV_ON_ACT_TIME": 41667
  
  "FRZN_ROOM6_DEFRST_STT_FROM_SCADA": 40602
  "FRZN_ROOM6_DEFRST_STP_FROM_SCADA": 40602
  "FRZN_ROOM6_DFRST_LLSV_CLS_TIME": 41674
  "FZN_ROOM6_DFST_LLSV_CLS_ACT_TIM": 41672
  "FRZN_ROOM6_DFRT_FAN_UNT_OFF_TIM": 41673
  "FRN_RM6_DFRT_FAN_UNT_OFF_ACT_TIM": 41676
  "FRZN_ROOM6_HGSV_ON_TIME": 41677
  "FRZN_ROOM6_HGSV_ON_TIME_ACT_TIME": 41678
  "FRZN_ROOM6_DFRST_PUMP_ON_TIME": 41679
  "FRZN_ROM6_DFST_PUMP_ON_ACT_TIME": 41680
  "FRZN_ROM6_DFRST_LLSV_ON_TIME": 41681
  "FRZN_ROM6_DFRST_LLSV_ON_ACT_TIME": 41682
  #"FROZEN_ANTE_ROOM_CLTR_STS": 1500
  #"FROZEN_ANTE_ROOM_RUN_HR": 1502
  "LLSV_AC_UNIT_1_2_FRN_RM_1_CTRL_STS": 42052
  "HSV_AC_UT_1_2_FZN_RM_1_CTRL_STS": 42054
  "ICLX_AC_UT_1_2_FZN_RM_1_CTRL_STS": 42056
  "LSV_AC_UT_1_2_FRN_RM_2_CTRL_STS": 42058
  "HSV_AC_UT_1_2_FZN_RM_2_CTRL_STS": 42060
  "ICLX_AC_UT_1_2_FZN_RM_2_CTRL_STS": 42062
  "LSV_AC_UT_1_2_FRN_RM_3_CTRL_STS": 42064
  "HSV_AC_UT_1_2_FZN_RM_3_CTRL_STS": 42066
  "ICLX_AC_UT_1_2_FZN_RM_3_CTRL_STS": 42068
  "LSV_AC_UT_1_2_FRN_RM_4_CTRL_STS": 42071
  "HSV_AC_UT_1_2_FZN_RM_4_CTRL_STS": 42070
  "ICLX_AC_UT_1_2_FZN_RM_4_CTRL_STS": 42072
  "LSV_AC_UT_1_2_FRN_RM_5_CTRL_STS": 42074
  "HSV_AC_UT_1_2_FZN_RM_5_CTRL_STS": 42076
  "ICLX_AC_UT_1_2_FZN_RM_5_CTRL_STS": 42078
  "LSV_AC_UT_1_2_FRN_RM_6_CTRL_STS": 42080
  "HSV_AC_UT_1_2_FZN_RM_6_CTRL_STS": 42082
  "ICLX_AC_UT_1_2_FZN_RM_6_CTRL_STS": 42084