hmis:
  - name: "Panelview 800 HMI Comp-A"
    ip: "192.168.1.6"
    port: 502
    auth_url: "http://192.168.1.6/login"
    username: "admin"
    password: "password123"
  - name: "Panelview 800 HMI Comp-B"
    ip: "192.168.1.8"
    port: 502
    auth_url: "http://192.168.1.8/login"
    username: "user"
    password: "password456"
  - name: "Panelview 800 HMI Comp-C"
    ip: "192.168.1.10"
    port: 502
    auth_url: "http://192.168.1.10/login"
    username: "admin"
    password: "password123"
  - name: "Panelview 800 HMI Comp-D"
    ip: "192.168.1.12"
    port: 502
    auth_url: "http://192.168.1.12/login"
    username: "user"
    password: "password789"
  - name: "Panelview HMI Comp-4 Viltor"
    ip: "192.168.1.20"
    port: 502
    auth_url: "http://192.168.1.20/login"
    username: "user"
    password: "password789"