data_points:
  EVAP_COND_1_CTRL_STS:
    register: 42022
    bits:
      - bit_name: START
        bit: 0
      - bit_name: STOP
        bit: 1
      - bit_name: AUTO/MANUAL
        bit: 2
      - bit_name: RESET
        bit: 4
      - bit_name: PUMP TRIP
        bit: 6
      - bit_name: LOCAL/REMOTE
        bit: 7
      - bit_name: PUMP ON
        bit: 9
      - bit_name: FAIL TO START
        bit: 12

  EVAP_COND_2_CTRL_STS:
    register: 42023
    bits:
      - bit_name: START
        bit: 0
      - bit_name: STOP
        bit: 1
      - bit_name: AUTO/MANUAL
        bit: 2
      - bit_name: RESET
        bit: 4
      - bit_name: PUMP TRIP
        bit: 6
      - bit_name: LOCAL/REMOTE
        bit: 7
      - bit_name: PUMP ON
        bit: 9
      - bit_name: FAIL TO START
        bit: 12

  EVAP_COND_3_CTRL_STS:
    register: 42037
    bits:
      - bit_name: START
        bit: 0
      - bit_name: STOP
        bit: 1
      - bit_name: AUTO/MANUAL
        bit: 2
      - bit_name: RESET
        bit: 4
      - bit_name: PUMP TRIP
        bit: 6
      - bit_name: LOCAL/REMOTE
        bit: 7
      - bit_name: PUMP ON
        bit: 9
      - bit_name: FAIL TO START
        bit: 12

  COMP_1_WR:
    register: 41336
    bits:
      - bit_name: START
        bit: 0
      - bit_name: STOP
        bit: 1
      - bit_name: AUTO/MANUAL
        bit: 2
      - bit_name: LOAD
        bit: 3
      - bit_name: UNLOAD
        bit: 4
      - bit_name: PUMP MANUAL
        bit: 5
      - bit_name: ACCEPT
        bit: 6
      - bit_name: RESET
        bit: 7
      - bit_name: PUMP AUTO
        bit: 9

  COMP_2_WR:
    register: 41340
    bits:
      - bit_name: START
        bit: 0
      - bit_name: STOP
        bit: 1
      - bit_name: AUTO/MANUAL
        bit: 2
      - bit_name: LOAD
        bit: 3
      - bit_name: UNLOAD
        bit: 4
      - bit_name: PUMP MANUAL
        bit: 5
      - bit_name: ACCEPT
        bit: 6
      - bit_name: RESET
        bit: 7
      - bit_name: PUMP AUTO
        bit: 9

  COMP_3_WR:
    register: 41344
    bits:
      - bit_name: START
        bit: 0
      - bit_name: STOP
        bit: 1
      - bit_name: AUTO/MANUAL
        bit: 2
      - bit_name: LOAD
        bit: 3
      - bit_name: UNLOAD
        bit: 4
      - bit_name: PUMP MANUAL
        bit: 5
      - bit_name: ACCEPT
        bit: 6
      - bit_name: RESET
        bit: 7
      - bit_name: PUMP AUTO
        bit: 9
