data_points:
  "SUCTION PRESSURE": 40001
  "DISCHARGE PRESSURE": 40003
  "OIL PRESSURE AFTER PUMP": 40005
  "OIL PRESSURE AFTER FILTER": 40007
  "SUCTION TEMPERATURE": 40009
  "DELTA OP": 40017
  "DISCHARGE TEMPERATURE": 40011
  "OIL TEMPERATURE": 40013
  "SEPARATOR TEMPERATURE": 40015
  "CAPACITY CONTROL": 40023
  "SV POSITION": 40019
  "MOTOR CURRENT": 40021
  "RUNNING HOURS": 40025
 # "COMPRESSOR STATUS": 41338
