data_points:
  "COMPRESSOR START": 40175
  "COMPRESSOR STOP": 40176
  "SLIDE VALVE MANUAL/AUTO PB": 40177
  "LOAD PB": 40178
  "UNLOAD PB": 40179
  "PUMP SELECTOR SWITCH MAN MODE": 40180
  "ACCEPT PB": 40181
  "RESET PB": 40182
  "MODBUS MODE": 40183
  "PUMP SELECTOR SWITCH AUTO MODE": 40184
