data_points:
  "COMPRESSOR START": 40200
  "COMPRESSOR STOP": 40201
  "LOAD MODE ENABLE": 40202
  "UNLOAD MODE ENABLE": 40203
  "RESET FAULT": 40204
  "REMOTE MODE ENABLE": 40205
  "LOCAL MODE ENABLE": 40206
  "AUTO MODE ENABLE": 40207
  "MANUAL MODE ENABLE": 40208
  "SHUTDOWN MODE ENABLE": 40209
