viltor_comp:
  - name: "Viltor Compressor 1"
    ip: "192.168.1.13"
    port: 502
  - name: "Micro820 Comp-2 Viltor"
    ip: "192.168.1.15"
    port: 502
  - name: "Micro820 Comp-3 Viltor"
    ip: "192.168.1.17"
    port: 502
#  - name: "Micro820 Comp-4 Viltor"
#    ip: "192.168.1.19"
#    port: 502