data_points:
  MOD_START:
    register: 40007
    bit: 0
  MOD_STOP:
    register: 40007
    bit: 1
  MOD_SV_MAN_AUTO:
    register: 40007
    bit: 2
  MOD_SV1:
    register: 40007
    bit: 3
  MOD_SV2:
    register: 40007
    bit: 4
  MOD_SV3:
    register: 40007
    bit: 5
  MOD_SV4:
    register: 40007
    bit: 6
